[package]
name = "enumizer"
version = "0.1.0"
edition = "2024"
description = "simple macros for generating enums that are equivalent and convertible to standard library enums"
license = "BSD-3-Clause"

[dependencies]
paste = "1"
